### ISSUE TITLE
esp32 improvements

### ISSUE THREAD

**Issue by shawn-phy** [Dungeons-of-dragons/Hardware#1]
## potential improvement areas
@BarbraGitonga; 
1. We **could** add a power switch/button from the main power supply. 
2. An led from the power supplies too **would** be useful in debugging. 
3. due to the working principle of the buck converter, it outputs both a ripple voltage(the exact module we are using has a 150 kHz switching frequency) and harmonics that I am not sure are good for the ESP32. We **should** add a ceramic capacitor between the 5v and GND of the esp32 or alternatively make a passive RC lowpass filter from the buck converter. 
4. the j1 connector for the fan should be 2 pin and it should be triggered from the relay. 
5. the u6(the MQ2)  block should be 3 pin not 4 pin as can be seen in the footprint editor.
6. the second buck converter(3.3 v) looks redundant, the esp32 can supply power for the RFID and DHT11. We **can** remove the second buck converter. 
7. The U3 connector **should** be 3 pin not 4 pin. 
8. The SCK(I2c) for the LCD screen is different from the SCL(SPI) for the RFID.

**Comment by BarbraGitonga** [comment]
- The power switch button has been added. (haven't pushed latest changes)
- The the relay used for the fan is an external module. not on the PCB. The three pins are to take out power to the fan and relay and one pin for the signal pin of the relay.
- The second 3.3V buck converter is also used to power the esp32, not just the sensors. also because of the position of the 3V3 output of the esp32, having another source of 3.3V is advantageous in routing.
- The MQ2 has 4 pins, only three are being used, but the four holes are necessary for mounting on the PCB. the A0 pin is a do not connect.
- Noted for the rest.

**Comment by shawn-phy** [comment]
@BarbraGitonga ,I missed that bit on powering the esp32. Nice catch.

**Comment by shawn-phy** [comment]
The recent changes seem to be ok, other people could review to ensure we didn't miss sth. For now this issue will be closed.
